CREATE TABLE CONTACTO(
    id_contacto INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(100),
    sexo VARCHAR (100),
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    email VARCHAR(100),
    comentario VARCHAR(400)
);