CREATE DATABASE DATOS_COVID;
USE DATOS_COVID;


CREATE TABLE DATOS_USUARIOS(
    id_DUsuario INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(100),
    sexo VARCHAR(2),
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DESCRIBE DATOS_USUARIOS;
INSERT INTO DATOS_USUARIOS(nombre,sexo)VALUES('Mi nombre', 'f');
SELECT * FROM DATOS_USUARIOS;